CREATE TABLE park(
    id SERIAL PRIMARY KEY,
    name VARCHAR(250) NOT NULL
)
CREATE TABLE location(
    id SERIAL PRIMARY KEY,
    code INTEGER
)

CREATE TABLE park(
    id SERIAL PRIMARY KEY,
    name VARCHAR(250) NOT NULL
)