CREATE TABLE park(
    id SERIAL PRIMARY KEY,
    name VARCHAR(250) NOT NULL
)

CREATE TABLE park(
    id SERIAL PRIMARY KEY,
    name VARCHAR(250) NOT NULL
)
CREATE TABLE park(
    id SERIAL PRIMARY KEY,
    name VARCHAR(250) NOT NULL
)